services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
    Common\Infrastructure\Exception\Symfony\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    #User\Infrastructure\Schedule\Symfony\ScheduleProvider:
    #    public: true
