services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
    Common\Infrastructure\Exception\Symfony\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    #User\Infrastructure\Schedule\Symfony\ScheduleProvider:
    #    public: true

    # COMMAND HANDLER
    Common\Application\Bus\Port\CommandBus:
        class: Common\Infrastructure\Bus\Command\CommandBus

    Common\Application\Handlers\Command\Port\TransactionManager:
        class: Common\Infrastructure\Persistence\Doctrine\Transaction\TransactionManager
        public: true

    Iam\Domain\:
        resource: '../../../src/Domain/'

    Common\Application\Container\Port\ServiceContainer:
        class: Common\Infrastructure\Container\Symfony\ServiceContainer
        arguments:
            $container: '@service_container'