services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    Iam\Domain\Repository\Port\UserRepository:
        class: Iam\Infrastructure\Persistence\Doctrine\UserRepository
