services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    User\Application\Ports\Output\Repository\UserRepository:
        class: User\Infrastructure\Persistence\Doctrine\UserRepository

    User\Domain\Services\RegisterUserService:
        public: true