services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    Iam\Domain\Ports\Output\Repository\UserRepository:
        class: Iam\Infrastructure\Persistence\Doctrine\UserRepository
