version: '2'
services:
  php:
    build: ./docker/php
    volumes:
        - ./:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    networks:
      - service_network

  nginx:
    build: ./docker/nginx
    links:
        - php
    volumes_from:
        - php
    ports:
      - 8008:80
    networks:
      - service_network

networks:
  service_network:
    external: true