services:
  gateway-service:
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
