services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # COMMAND HANDLER
    User\Application\Ports\Output\Bus\CommandBus:
        class: User\Infrastructure\Adapter\Bus\Command\CommandBus

    # REGISTER USER COMMAND
    User\Application\Handlers\Command\RegisterUserCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', method: 'handle' }