services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # QUERY HANDLER
    User\Application\Ports\Output\Bus\EventBus:
        class: User\Infrastructure\Adapter\Bus\Event\EventBus

    User\Infrastructure\Adapter\Bus\Event\EventHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', method: 'handle' }