services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    User\Application\Repository\OutboxRepository:
        class: User\Infrastructure\Adapter\Persistence\Memory\OutboxRepository
        public: true
